### ISSUE TITLE
Chained task produces nvim errors, doesn't carry out fully if the first task's output is set to `terminal`

### ISSUE THREAD

**Issue by Filip62** [pianocomposer321/yabs.nvim#45] opened 2022-02-27 00:04 UTC
Hi, I am setting up the configuration for this amazing plugin but I ran into an issue where if I run a chained task that consist of a build and a run task(which is run after the build task is finished) I get this error.

`build_and_run` is the chained task in question.

Running NVIM v0.6.1, thanks.

```
Error executing luv callback:                                                                                                                            
vim/shared.lua:191: E5560: vimL function must not be called in a lua loop callback                                                                       
stack traceback:                                                                                                                                         
        [C]: in function 'func'                                                                                                                          
        vim/shared.lua:191: in function 'tbl_map'                                                                                                        
        ...nvim/site/pack/packer/start/yabs.nvim/lua/yabs/utils.lua:6: in function 'expand'                                                              
        .../nvim/site/pack/packer/start/yabs.nvim/lua/yabs/task.lua:55: in function 'run'                                                                
        ...m/site/pack/packer/start/yabs.nvim/lua/yabs/language.lua:89: in function 'run_task'                                                           
        [string "..."]: in function '_user_on_exit'                                                                                                      
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:243: in function '_shutdown'                                                         
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:46: in function <.../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:37>     
        [C]: in function 'setqflist'                                                                                                                     
        ...ack/packer/start/yabs.nvim/lua/yabs/outputs/quickfix.lua:9: in function 'cb'                                                                  
        vim.lua:285: in function <vim.lua:285>
```

Here is my configuration.

``` lua
{
  'pianocomposer321/yabs.nvim',
  requires = { 'nvim-lua/plenary.nvim' },
  config = function ()
    require('yabs'):setup({
      languages = { -- List of languages in vim's `filetype` format
        cpp = {
          default_task = 'build_and_run',
          tasks = {
            build = {
              command = 'make -j12',
              output = 'quickfix', -- Where to show output of the
              -- command. Can be `buffer`,
              -- `consolation`, `echo`,
              -- `quickfix`, `terminal`, or `none`
              opts = { -- Options for output (currently, there's only
              -- `open_on_run`, which defines the behavior
              -- for the quickfix list opening) (can be
              -- `never`, `always`, or `auto`, the default)
              open_on_run = 'never',
            },
          },
          run = { -- You can specify as many tasks as you want per
          -- filetype
          command = './build/izg_lab_02',
          output = 'quickfix',
          opts = { -- Options for output (currently, there's only
          -- `open_on_run`, which defines the behavior
          -- for the quickfix list opening) (can be
          -- `never`, `always`, or `auto`, the default)
          open_on_run = 'never',
        }
        },
        build_and_run = { -- Setting the type to lua means the command
        -- is a lua function
        command = function()
          -- The following api can be used to run a task when a
          -- previous one finishes
          -- WARNING: this api is experimental and subject to
          -- changes
          require('yabs'):run_task('build', {
            -- Job here is a plenary.job object that represents
            -- the finished task, read more about it here:
            -- https://github.com/nvim-lua/plenary.nvim#plenaryjob
            on_exit = function(Job, exit_code)
              -- The parameters `Job` and `exit_code` are optional,
              -- you can omit extra arguments or
              -- skip some of them using _ for the name
              if exit_code == 0 then
                require('yabs').languages.cpp:run_task('run')
              end
            end,
          })
        end,
        type = 'lua',
          output = 'quickfix',
          opts = { -- Options for output (currently, there's only
          -- `open_on_run`, which defines the behavior
          -- for the quickfix list opening) (can be
          -- `never`, `always`, or `auto`, the default)
          open_on_run = 'never',
        }
      },
    },
  },
},
-- tasks = { -- Same values as `language.tasks`, but global
-- build = {
--   command = 'echo building project...',
--   output = 'terminal',
-- },
-- run = {
--   command = 'echo running project...',
--   output = 'echo',
-- },
-- optional = {
--   command = 'echo runs on condition',
--   -- You can specify a condition which determines whether to enable a
--   -- specific task
--   -- It should be a function that returns boolean,
--   -- not a boolean directly
--   -- Here we use a helper from yabs that returns such function
--   -- to check if the files exists
--   condition = require('yabs.conditions').file_exists('filename.txt'),
-- },
--   },
--   opts = { -- Same values as `language.opts`
--   output_types = {
--     quickfix = {
--       open_on_run = 'always',
--     },
--   },
-- },
})
    end
  },
```

**Comment by pianocomposer321** [comment] 2022-02-27 00:31
Thank you for opening an issue!

I can't really test this right now, but I think the problem might be the `output` key of the `build_and_run` task. It should be omitted, not set to `quickfix`. Setting it causes the plugin to try to send the output of the command to the quickfix list, but because it's not a shell command but a lua function (from the `type = "lua"` key), this causes unexpected results.

Let me know if this fixes it! Even if it does, I think we can leave the issue open, because I think this situation should provide a more helpful error message.

**Comment by Filip62** [comment] 2022-02-27 09:36
That was actually just a thing I tried when it was erroring out, I thought that maybe the issue is that it is missing. Without the `output` key, this is the error I get.

```
Error executing luv callback:                                                                                                                            
vim/shared.lua:191: E5560: vimL function must not be called in a lua loop callback                                                                       
stack traceback:                                                                                                                                         
        [C]: in function 'func'                                                                                                                          
        vim/shared.lua:191: in function 'tbl_map'                                                                                                        
        ...nvim/site/pack/packer/start/yabs.nvim/lua/yabs/utils.lua:6: in function 'expand'                                                              
        .../nvim/site/pack/packer/start/yabs.nvim/lua/yabs/task.lua:55: in function 'run'                                                                
        ...m/site/pack/packer/start/yabs.nvim/lua/yabs/language.lua:89: in function 'run_task'                                                           
        [string "..."]: in function '_user_on_exit'                                                                                                      
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:243: in function '_shutdown'                                                         
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:46: in function <.../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:37>
```

Thank you for taking the time to look at this.

**Comment by pianocomposer321** [comment] 2022-02-27 21:40
I believe this is fixed on the hotfix branch. Can you test it out and let me know?

Thanks.

**Comment by Filip62** [comment] 2022-02-27 22:14
The error definitely went away but I don't think the `on_exit` function actually runs.
I put these notify calls in the `on_exit` function and they never appear in the echo or :messages.

`"Are we running?!"` does appear and the build task finishes with exit code 0 (at least make in the terminal does) but the run part/on_exit function probably isn't executed.

```lua
        build_and_run = { -- Setting the type to lua means the command
        -- is a lua function
        command = function()
          -- The following api can be used to run a task when a
          -- previous one finishes
          -- WARNING: this api is experimental and subject to
          -- changes
          vim.notify("Are we running?!", vim.log.levels.ERROR)
          require('yabs'):run_task('build', {
            -- Job here is a plenary.job object that represents
            -- the finished task, read more about it here:
            -- https://github.com/nvim-lua/plenary.nvim#plenaryjob
            on_exit = function(Job, exit_code)
              -- The parameters `Job` and `exit_code` are optional,
              -- you can omit extra arguments or
              -- skip some of them using _ for the name
              vim.notify("Is the check failing?", vim.log.levels.ERROR)
              if exit_code == 0 then
                vim.notify("Going to run!", vim.log.levels.ERROR)
                require('yabs').languages.cpp:run_task('run')
              end
            end,
          })
        end,
        type = 'lua',
      },
```

**Comment by pianocomposer321** [comment] 2022-03-05 18:35
It works for me with the following config:

```lua
require('yabs'):setup {
  languages = { -- List of languages in vim's `filetype` format
   cpp = {
      default_task = 'build_and_run',
      tasks = {
        build = {
          command = 'echo building',
          output = 'quickfix' -- Where to show output of the
        },
        run = { -- You can specify as many tasks as you want per
          command = 'echo running',
          output = 'terminal'
        },
        build_and_run = { -- Setting the type to lua means the command
          command = function()
            require('yabs'):run_task('build', {
              on_exit = function(Job, exit_code)
                if exit_code == 0 then
                  require('yabs').languages.cpp:run_task('run')
                end
              end
            })
          end,
          type = 'lua'
        },
      },
    },
  },
}
```

**Comment by Filip62** [comment] 2022-03-06 20:07
Okay, we are onto something now.

If the first task's output is set to `quickfix` the chaining works as expected, but when I change it to `terminal`, it doesn't execute the run task.

Same behavior with your config from the last message.

```lua
require('yabs'):setup {
  languages = {
    cpp = {
      default_task = 'build_and_run',
        tasks = {
          build = {
            command = 'make -j12 -B',
            output = 'quickfix' -- This can't be 'terminal'
          },
          run = {
          command = './build/izg_lab_02',
          output = 'terminal'
          },
          build_and_run = {
          command = function()
            require('yabs'):run_task('build', {
              on_exit = function(Job, exit_code)
                if exit_code == 0 then
                  require('yabs').languages.cpp:run_task('run')
                end
              end
            })
          end,
          type = 'lua'
        },
      },
    },
  },
}
```

**Comment by pianocomposer321** [comment] 2022-05-05 01:55
The problem is that the terminal output doesn't support chaining tasks, because there's no way to tell when the command finishes with the terminal.

In any case, I've deprecated this version of yabs in favor of the version I rewrote completely recently, you can check out [my blog post](https://pianocomposer321.github.io/2022/05/03/why-im-rewriting-yabs.html) for more details.

**Closed by pianocomposer321** 2022-05-05 01:55 UTC
